import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../../assets/root.css';
import NavBar from '@/components/navigationBar';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <div className="default-margin-body">
                    <NavBar />
                </div>
                {children}
            </body>
        </html>
    );
}
