import type { Metadata } from 'next';
import '../../assets/root.css';
import NavBar from '@/components/navigationBar';
import Providers from '@/redux/providerComponent';
import { getServerSession, Session } from 'next-auth';
import { authOptions } from '@/utils/authOptions';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session: Session | null = await getServerSession(authOptions);

    return (
        <html lang="en">
            <body>
                <Providers>
                    <div className="default-margin-body">
                        <NavBar session={session} />
                    </div>
                    {children}
                </Providers>
            </body>
        </html>
    );
}
